src/books/urls.py
from django.urls import path

from books.views import (
    AuthorListView,
    BookListView,
    BookUpdateView,
    BooksOnShelfListView,
    index,
)


app_name = "books"

urlpatterns = [
    path("", index, name="index"),
    path("authors", AuthorListView.as_view(), name="list_authors"),
    path("author_books/<int:author_id>/", BookListView.as_view(), name="author_books"),
    path("shelfs", BooksOnShelfListView.as_view(), name="shelfs"),
    path(
        "shelfs/<int:shelf_id>", BooksOnShelfListView.as_view(), name="books_on_shelf"
    ),
    path(
        "edit-book-on-shelf/<int:pk>/",
        BookUpdateView.as_view(),
        name="edit_book",
    ),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls", namespace="books")),
]

src/books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title = models.CharField("Название", max_length=150)
    author = models.ForeignKey(
        "books.Author",
        verbose_name="Автор",
        on_delete=models.CASCADE,
        related_name="books",
    )

    class Meta:
        ordering = ["author", "title"]

    def __str__(self):
        return f"{self.title} [{self.author}]"


class Author(models.Model):
    full_name = models.CharField("ФИО Автора", max_length=100)

    def __str__(self):
        return self.full_name


class Shelf(models.Model):
    id = models.IntegerField("Номенр полки", primary_key=True)

    def __str__(self):
        return f"Полка №{self.id}"


class BookOnShelf(models.Model):
    book = models.OneToOneField(
        "books.Book",
        verbose_name="Книга",
        on_delete=models.CASCADE,
        default=None,
    )
    shelf = models.ForeignKey(
        "books.Shelf", on_delete=models.CASCADE, related_name="books_on_shelf"
    )
    position = models.PositiveIntegerField("Позиция на полке", null=True, blank=True)

    class Meta:
        ordering = ["shelf", "position"]

    def __str__(self):
        return f"[{self.shelf}] ({self.position}) {self.book}"

    def save(self, *args, update_fields=None, **kwargs):
        if (
            not self.position
            and not self.__class__.objects.filter(shelf=self.shelf).exists()
        ):
            self.position = 1
        elif (
            not self.position
            and not update_fields
            and self.__class__.objects.filter(shelf=self.shelf).exists()
        ):
            self.position = (
                self.__class__.objects.filter(shelf=self.shelf).last().position + 1
            )

        super().save(*args, **kwargs)

    def change_position(self, to_book):
        to_book.position, self.position = self.position, to_book.position
        to_book.save(update_fields=["position"])
        self.save(update_fields=["position"])

src/books/forms.py
from django import forms
from .models import BookOnShelf


class BookOnShelfForm(forms.Form):
    def __init__(self, instance, *args, **kwargs):
        super(BookOnShelfForm, self).__init__(*args, **kwargs)
        self.fields["position"] = forms.ModelChoiceField(queryset=None)
        qs = BookOnShelf.objects.filter(shelf=instance.shelf).exclude(pk=instance.pk)
        self.fields["position"].queryset = qs
        self.object = instance

    def save(self, *args, **kwargs):
        selected_obj = self.cleaned_data["position"]
        self.object.change_position(selected_obj)

src/books/views.py
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.shortcuts import render
from django.urls import reverse

from books.forms import BookOnShelfForm
from books.models import Author, Book, BookOnShelf, Shelf


def index(request):
    template = "index.html"
    context = {"books": Book.objects.all().select_related("author")}
    context["shelfs"] = Shelf.objects.all()
    return render(request, template, context)


class AuthorListView(ListView):
    model = Author
    template_name = "authors.html"


class BookListView(ListView):
    model = Book
    template_name = "books_by_author_list.html"

    def get_queryset(self, **kwargs):
        author_id = self.kwargs.get("author_id")
        if author_id:
            return super().get_queryset().filter(author_id=author_id)
        return super().get_queryset()


@method_decorator(never_cache, name="dispatch")
class BooksOnShelfListView(ListView):
    model = BookOnShelf
    template_name = "books_on_shelf_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shelfs"] = Shelf.objects.all()
        return context

    def get_queryset(self):
        shelf_id = self.kwargs.get("shelf_id")
        if shelf_id:
            return super().get_queryset().filter(shelf_id=shelf_id)
        return super().get_queryset()


class BookUpdateView(UpdateView):
    model = BookOnShelf
    form_class = BookOnShelfForm
    template_name = "update_book.html"

    def get_success_url(self):
        shelf_id = self.get_object().shelf.pk
        url = reverse("books:books_on_shelf", kwargs={"shelf_id": shelf_id})
        return url

src/templates/authors.html
{% extends 'base.html' %}

{% block title %}Все авторы{% endblock title %}

{% block content %}

{% for shelf in shelfs %}
<a href="{% url 'books:books_on_shelf' shelf_id=shelf.pk %}">{{shelf}}</a>
{% endfor %}

<hr>

{% for obj in object_list %}
{{obj}}<br>
{% endfor %}

<hr>
<a href="{% url 'books:index' %}">На главную</a>

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
  {% block js %} {% endblock js %}
</html>

src/templates/books_by_author_list.html
{% extends 'base.html' %}

{% block title %}Все авторы{% endblock title %}

{% block content %}

{% for shelf in shelfs %}
<a href="{% url 'books:books_on_shelf' shelf_id=shelf.pk %}">{{shelf}}</a>
{% endfor %}

<hr>

{% for obj in object_list %}
{{obj}} [{{obj.bookonshelf.shelf}}]<br>
{% endfor %}

<hr>
<a href="{% url 'books:index' %}">На главную</a>

{% endblock content %}

src/templates/books_on_shelf_list.html
{% extends 'base.html' %}

{% block title %}Все авторы{% endblock title %}

{% block content %}

{% for shelf in shelfs %}
<a href="{% url 'books:books_on_shelf' shelf_id=shelf.pk %}">{{shelf}}</a>
{% endfor %}

<hr>

{% for obj in object_list %}
{{obj}} -- <a href="{% url 'books:edit_book' pk=obj.pk %}">Изменить положение на
  полке</a><br>
{% endfor %}

<hr>
<a href="{% url 'books:index' %}">На главную</a>

{% endblock content %}

src/templates/index.html
{% extends 'base.html' %}
{% block title %} Главная {% endblock title %}
{% block content %}
<h1>Моя библиотека</h1>

{% for shelf in shelfs %}
<a href="{% url 'books:books_on_shelf' shelf_id=shelf.pk %}">{{shelf}}</a>
{% endfor %}
<hr>

<a href="{% url 'books:list_authors' %}">Все авторы</a>
<a href="{% url 'books:shelfs' %}">Показать полки</a><br>
<hr>
<h3>Все книги</h3>
{% for book in books %}
<a href="{% url 'books:author_books' author_id=book.author.id %}">{{book.author}}</a>
{{book.title}}<br>
{% endfor %}
{% endblock content %}

src/templates/list.html
{% extends 'base.html' %}

{% block title %}Все авторы{% endblock title %}

{% block content %}

{% for shelf in shelfs %}
{{shelf}}
{% endfor %}

<hr>

{% for obj in object_list %}
{{obj}} [{{obj.bookonshelf.shelf}}]<br>
{% endfor %}

{% endblock content %}

src/templates/update_book.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="POST"> {% csrf_token %}

  {{form.as_p}}
  <button type="submit">Сохранить</button>
</form>
<br>
<form action="{% url 'books:shelfs' %}">
  <input type="submit" value="Обратно к полкам!" />
</form>

{% endblock content %}